# Generated by Django 6.0.6 on 2026-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sos_alert', 'SOS Alert'), ('escalation', 'Escalation'), ('approval', 'Approval Update'), ('general', 'General')], max_length=20, unique=True)),
                ('title_template', models.CharField(help_text='Use {name}, {category} as placeholders', max_length=150)),
                ('body_template', models.TextField(help_text='Use {name}, {category}, {location} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
