# Generated by Django 6.0.6 on 2026-07-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_escalationconfig_sosalert_is_escalated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EscalationConfig',
        ),
    ]
