# Generated by Django 6.0.6 on 2026-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_delete_escalationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_window_minutes', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='escalationlog',
            name='escalated_to',
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_to_name',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalated_to_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
