# Generated by Django 6.0.6 on 2026-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_sosalert_assigned_at_sosalert_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
