# Generated by Django 6.0.6 on 2026-07-23 09:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_residentprofile_approval_status_residentprofile_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=users.models.otp_expiry_time),
        ),
    ]
