# Generated by Django 6.0.6 on 2026-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='availability_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
