# Generated by Django 6.0.6 on 2026-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_volunteerprofile_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='resident_documents/address/'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
